### ISSUE TITLE
Discuss strategy for URL slugs for areas, mediums, etc.

### ISSUE THREAD

**Issue by rnackman** [mplusmuseum/mplusmuseum-www#109]

**Comment by micahwalter** [comment]
/ = Homepage - For now this will be "collections home page" but really it's a temp holding page

/collections - The actual home page for collections ( note the `s` since there will be numerous collections )

/collections/objects - currently these are called artworks, but they should be objects
/collections/objects/brooklyn-int - brooklyn-int ID for the individual object

/collections/makers
/collections/makers/brooklyn-int ( not sure makers will stick, but lets use it for now )

I think we should skip the "slug" bit for now, since it's a little problematic and only really an SEO thing.

**Comment by erchaves** [comment]
I'll pick this up again and make these changes.
